// GENERATED by mt5/tools/gen_params.py -- DO NOT EDIT. Regenerate instead.
// Strategies/S004_FVG/Params.mqh
// S004-intraday (H4 FVG bounce, Asia session, FX) rule constants.
// Session hours and the cutoff are on the broker's EET/EEST clock,
// DST-aware on EUROPEAN dates -- measured from the M15 data by
// backtest/run_s004_clock_probe.py, never assumed to be a fixed offset.
// The daily cap is portfolio-wide: the EA counts entries across all
// S004_SYMBOLS together (see backtest/run_s004_intraday.py).
#ifndef STRATEGIES_S004_FVG_PARAMS_MQH
#define STRATEGIES_S004_FVG_PARAMS_MQH

#define S004_RR                              3.0          // S004_INTRADAY.rr: TP distance = rr * risk
#define S004_BUFFER_PIPS                     2.0          // fvg_mtf.BUFFER_PIPS: stop sits this far beyond the zone's far edge
#define S004_WINDOW_BARS                     96           // fvg_mtf.WINDOW_BARS: M15 bars a zone stays armed after its first touch
#define S004_SESSION_FIRST_HOUR              0            // S004_INTRADAY.entry_hours start (Asia 00:00, session clock)
#define S004_SESSION_LAST_HOUR               6            // S004_INTRADAY.entry_hours end, inclusive (06:59)
#define S004_INTRADAY_CUTOFF_MINUTE          1365         // prop rule 1: everything open is closed on the 22:45 bar
#define S004_COST_INCLUSIVE_SIZING           true         // prop rule 2: size on (stop + spread), so a full stop is exactly -1R
#define S004_MAX_TRADES_PER_DAY              2            // prop rule 3: entries per session day across ALL symbols, not per symbol
#define S004_SYMBOL_COUNT                    7            // S004_INTRADAY.pairs count
#define S004_SYMBOLS                         "GBPJPY,EURUSD,USDCHF,GBPUSD,EURJPY,USDJPY,AUDUSD" // S004_INTRADAY.pairs; entry order on ties is by symbol name, not this order
#define S004_CLOCK_TZ_RULE                   TZ_EET_EU_DST // s004_config.SESSION_TZ Europe/Bucharest (measured, see run_s004_clock_probe.py)
#define S004_MAGIC_PREFIX                    "S004"       // s004_config.MAGIC (labels)
#define S004_DEFAULT_RISK_PCT                1.0          // s004_config.RISK_PCT (EA input default)
#define S004_PARAMS_SOURCE                   "strategies/s004_config.py::S004_INTRADAY sha=8024c6e97f50" // provenance, logged by the EA at init

#endif // STRATEGIES_S004_FVG_PARAMS_MQH
