// GENERATED by mt5/tools/gen_params.py -- DO NOT EDIT. Regenerate instead.
// AlgoCore/GeneratedCore.mqh
// Shared constants from the Python bot base layer (bot/risk.py,
// bot/account_guard.py).
#ifndef ALGOCORE_GENERATEDCORE_MQH
#define ALGOCORE_GENERATEDCORE_MQH

#define ALGO_MIN_STOP_POINTS                 0.5          // bot/risk.py MIN_STOP_POINTS: below this a stop is 'no real stop'
#define ALGO_PCT                             100.0        // bot/account_guard.py PCT
#define ALGO_REASON_DAILY                    "account_daily_loss_guard" // bot/account_guard.py REASON_DAILY (log readers grep for it)
#define ALGO_REASON_MAX                      "account_max_loss_guard" // bot/account_guard.py REASON_MAX

#endif // ALGOCORE_GENERATEDCORE_MQH
