//+------------------------------------------------------------------+
//| Scripts/AlgoTrading/S021_SelfTest.mq5                            |
//| Self-test of the pure MQL5 pieces the S021 EA is built from,     |
//| against expectations produced by the Python source of truth:     |
//|                                                                  |
//|   clock   AlgoCore/Clock.mqh rule offsets vs Python zoneinfo      |
//|           (fixtures/clock_cases.csv)                             |
//|   levels  AlgoCore/Sessions.mqh + S021 Levels.mqh vs the backtest |
//|           engine's O / ADR14 / U / L per day                     |
//|           (fixtures/s021_m1.csv + fixtures/s021_levels.csv)      |
//|   sizing  AlgoCore/Sizing.mqh vs tests/bot/test_risk.py cases     |
//|   guard   AlgoCore/AccountGuard.mqh vs test_account_guard.py      |
//|                                                                  |
//| Fixtures are generated by `python -m mt5.tools.s021_fixtures`    |
//| into <Common>/Files/AlgoTrading/fixtures/ (see mt5/README.md).   |
//| Run: drag onto any chart. Result: Experts log + a JSON summary   |
//| in <Common>/Files/AlgoTrading/selftest/S021_selftest.json.       |
//+------------------------------------------------------------------+
#property copyright "AlgoTrading (Anton Malashenko)"
#property version   "1.00"
#property script_show_inputs

#include <AlgoCore/Clock.mqh>
#include <AlgoCore/Sessions.mqh>
#include <AlgoCore/Sizing.mqh>
#include <AlgoCore/AccountGuard.mqh>
#include <Strategies/S021_ORB/Levels.mqh>

#define SELFTEST_FIXTURE_DIR   "AlgoTrading/fixtures/"
#define SELFTEST_RESULT_DIR    "AlgoTrading/selftest"
#define SELFTEST_REL_TOLERANCE 1e-9
#define SELFTEST_ABS_TOLERANCE 1e-9
#define SELFTEST_MAX_REPORTED  20

input bool InpRequireFixtures = true; // Fail when fixture files are missing

int    g_passed=0;
int    g_failed=0;
int    g_reported=0;
string g_failures="";

void Check(const bool condition,const string name)
  {
   if(condition)
     {
      g_passed++;
      return;
     }
   g_failed++;
   if(g_reported<SELFTEST_MAX_REPORTED)
     {
      g_reported++;
      Print("FAIL ",name);
      g_failures+=(StringLen(g_failures)>0 ? "," : "")+"\""+name+"\"";
     }
  }

bool Near(const double actual,const double expected)
  {
   double scale=MathMax(1.0,MathAbs(expected));
   return MathAbs(actual-expected)<=MathMax(SELFTEST_ABS_TOLERANCE,SELFTEST_REL_TOLERANCE*scale);
  }

int OpenFixture(const string name)
  {
   return FileOpen(SELFTEST_FIXTURE_DIR+name,FILE_READ|FILE_CSV|FILE_ANSI|FILE_COMMON,',');
  }

ENUM_TZ_RULE RuleFromName(const string name)
  {
   if(name=="UTC")        return TZ_UTC;
   if(name=="EET_US_DST") return TZ_EET_US_DST;
   if(name=="EET_EU_DST") return TZ_EET_EU_DST;
   if(name=="CET_EU_DST") return TZ_CET_EU_DST;
   return TZ_FIXED;
  }

//--- clock ------------------------------------------------------------------
void TestClockFixed()
  {
   // US DST 2025: 2025-03-09 07:00 UTC .. 2025-11-02 06:00 UTC
   Check(!ClockIsUsDst(ClockMakeTime(2025,3,9,6,59)),"clock.us.before_start");
   Check(ClockIsUsDst(ClockMakeTime(2025,3,9,7,0)),"clock.us.at_start");
   Check(ClockIsUsDst(ClockMakeTime(2025,11,2,5,59)),"clock.us.before_end");
   Check(!ClockIsUsDst(ClockMakeTime(2025,11,2,6,0)),"clock.us.at_end");
   // EU DST 2025: 2025-03-30 01:00 UTC .. 2025-10-26 01:00 UTC
   Check(!ClockIsEuDst(ClockMakeTime(2025,3,30,0,59)),"clock.eu.before_start");
   Check(ClockIsEuDst(ClockMakeTime(2025,3,30,1,0)),"clock.eu.at_start");
   Check(!ClockIsEuDst(ClockMakeTime(2025,10,26,1,0)),"clock.eu.at_end");
   // server <-> UTC round trip on a weekday in each regime
   datetime summer_utc=ClockMakeTime(2025,7,15,14,30);
   datetime winter_utc=ClockMakeTime(2025,1,15,14,30);
   Check(ClockUtcToLocal(TZ_EET_US_DST,0,summer_utc)==summer_utc+3*CLOCK_SECONDS_PER_HOUR,"clock.eet_us.summer");
   Check(ClockUtcToLocal(TZ_EET_US_DST,0,winter_utc)==winter_utc+2*CLOCK_SECONDS_PER_HOUR,"clock.eet_us.winter");
   Check(ClockLocalToUtc(TZ_EET_US_DST,0,summer_utc+3*CLOCK_SECONDS_PER_HOUR)==summer_utc,"clock.eet_us.roundtrip");
   // S021 fixed-EST clock: 14:30 UTC is always 09:30 on the strategy clock
   Check(ClockMinuteOfDay(S021UtcToClock(summer_utc))==S021_SESSION_OPEN_MINUTE,"clock.s021.anchor_summer");
   Check(ClockMinuteOfDay(S021UtcToClock(winter_utc))==S021_SESSION_OPEN_MINUTE,"clock.s021.anchor_winter");
   Check(ClockParseHhMm("20:44")==20*60+44,"clock.parse.ok");
   Check(ClockParseHhMm("")==-1 && ClockParseHhMm("2:44")==-1 && ClockParseHhMm("24:00")==-1,"clock.parse.bad");
  }

void TestClockFixture()
  {
   int handle=OpenFixture("clock_cases.csv");
   if(handle==INVALID_HANDLE)
     {
      Check(!InpRequireFixtures,"clock.fixture_missing");
      return;
     }
   for(int i=0;i<3;i++)
      FileReadString(handle);              // header: rule,utc,offset_seconds
   int cases=0;
   while(!FileIsEnding(handle))
     {
      string rule_name=FileReadString(handle);
      if(StringLen(rule_name)==0)
         break;
      datetime utc=StringToTime(FileReadString(handle));
      int expected=(int)StringToInteger(FileReadString(handle));
      ENUM_TZ_RULE rule=RuleFromName(rule_name);
      int actual=ClockOffsetSecondsAtUtc(rule,0,utc);
      Check(actual==expected,StringFormat("clock.zoneinfo.%s.%s",rule_name,TimeToString(utc)));
      // local -> UTC is ambiguous only inside the DST hour, which always falls on a
      // weekend (no bars) -- round-trip is required on trading days only
      datetime local=utc+expected;
      MqlDateTime local_parts;
      TimeToStruct(local,local_parts);
      bool weekend=(local_parts.day_of_week==0 || local_parts.day_of_week==6);
      if(!weekend)
         Check(ClockLocalToUtc(rule,0,local)==utc,
               StringFormat("clock.roundtrip.%s.%s",rule_name,TimeToString(utc)));
      cases++;
     }
   FileClose(handle);
   Check(cases>0,"clock.fixture_empty");
   PrintFormat("clock fixture: %d cases",cases);
  }

//--- levels -----------------------------------------------------------------
void TestLevelsFixture()
  {
   // s021_meta.csv: key,value rows -- only server_tz_rule is needed here
   string rule_name="";
   int meta=OpenFixture("s021_meta.csv");
   if(meta!=INVALID_HANDLE)
     {
      while(!FileIsEnding(meta))
        {
         string key=FileReadString(meta);
         string value=FileReadString(meta);
         if(key=="server_tz_rule")
            rule_name=value;
        }
      FileClose(meta);
     }
   int handle=OpenFixture("s021_m1.csv");
   if(handle==INVALID_HANDLE || StringLen(rule_name)==0)
     {
      if(handle!=INVALID_HANDLE)
         FileClose(handle);
      Check(!InpRequireFixtures,"levels.m1_fixture_missing");
      return;
     }
   for(int i=0;i<5;i++)
      FileReadString(handle);              // header: time_server,open,high,low,close
   ENUM_TZ_RULE rule=RuleFromName(rule_name);

   datetime clock_times[];
   double opens[];
   double highs[];
   double lows[];
   int count=0;
   int capacity=0;
   while(!FileIsEnding(handle))
     {
      string time_text=FileReadString(handle);
      if(StringLen(time_text)==0)
         break;
      double open=StringToDouble(FileReadString(handle));
      double high=StringToDouble(FileReadString(handle));
      double low=StringToDouble(FileReadString(handle));
      FileReadString(handle);              // close (unused by the levels math)
      if(count>=capacity)
        {
         capacity=(capacity==0) ? 65536 : capacity*2;
         ArrayResize(clock_times,capacity);
         ArrayResize(opens,capacity);
         ArrayResize(highs,capacity);
         ArrayResize(lows,capacity);
        }
      datetime server_time=StringToTime(time_text);
      clock_times[count]=S021UtcToClock(ClockLocalToUtc(rule,0,server_time));
      opens[count]=open;
      highs[count]=high;
      lows[count]=low;
      count++;
     }
   FileClose(handle);
   PrintFormat("levels fixture: %d M1 bars, server rule %s",count,rule_name);

   DailySession sessions[];
   SessionWindow window=S021Window();
   int session_count=SessionsBuild(clock_times,opens,highs,lows,count,window,sessions);

   int expected_handle=OpenFixture("s021_levels.csv");
   if(expected_handle==INVALID_HANDLE)
     {
      Check(false,"levels.expected_fixture_missing");
      return;
     }
   for(int i=0;i<7;i++)
      FileReadString(expected_handle);     // day,valid_session,open,adr,upper,lower,stop_distance
   int days=0;
   int with_levels=0;
   while(!FileIsEnding(expected_handle))
     {
      string day_text=FileReadString(expected_handle);
      if(StringLen(day_text)==0)
         break;
      bool valid_session=(StringToInteger(FileReadString(expected_handle))==1);
      double open=StringToDouble(FileReadString(expected_handle));
      string adr_text=FileReadString(expected_handle);
      double upper=StringToDouble(FileReadString(expected_handle));
      double lower=StringToDouble(FileReadString(expected_handle));
      double stop_distance=StringToDouble(FileReadString(expected_handle));
      datetime day=StringToTime(day_text);
      days++;

      // session validity: the day appears in the MQL5 session list iff the engine accepted it
      bool found=false;
      for(int i=0;i<session_count;i++)
         if(sessions[i].day==day)
           {
            found=true;
            Check(Near(sessions[i].open,open),"levels.session_open."+day_text);
            break;
           }
      Check(found==valid_session,"levels.session_validity."+day_text);

      S021Levels levels;
      bool ok=S021ComputeLevels(sessions,session_count,day,open,levels);
      bool expected_ok=(adr_text!="nan" && StringLen(adr_text)>0);
      Check(ok==expected_ok,"levels.adr_available."+day_text);
      if(ok && expected_ok)
        {
         with_levels++;
         Check(Near(levels.adr,StringToDouble(adr_text)),"levels.adr."+day_text);
         Check(Near(levels.upper,upper),"levels.upper."+day_text);
         Check(Near(levels.lower,lower),"levels.lower."+day_text);
         Check(Near(levels.stop_distance,stop_distance),"levels.stop."+day_text);
        }
     }
   FileClose(expected_handle);
   PrintFormat("levels fixture: %d days compared, %d with levels",days,with_levels);
   Check(with_levels>0,"levels.none_compared");
  }

//--- sizing (mirrors tests/bot/test_risk.py) --------------------------------------
void TestSizing()
  {
   Check(Near(SizingLotsForRisk(25.0,50.0,1.0,0.01),0.5),"sizing.basic");
   Check(Near(SizingLotsForRisk(25.0,100000.0,1.0,0.01),0.01),"sizing.floor_min_lot");
   Check(Near(SizingLotsForRisk(25.0,5.0,1.0,0.01),5.0),"sizing.tight_stop");
   Check(Near(SizingLotsForRisk(25.0,ALGO_MIN_STOP_POINTS/2.0,1.0,0.01),0.01),"sizing.below_min_stop");
   Check(Near(SizingLotsForRisk(25.0,0.0,1.0,0.01),0.01),"sizing.zero_stop");
   Check(Near(SizingLotsForRisk(25.0,-5.0,1.0,0.01),0.01),"sizing.negative_stop");
   Check(Near(SizingLotsForRisk(25.0,50.0,0.0,0.01),0.01),"sizing.zero_mppl");
   Check(Near(SizingLotsForRisk(0.0,50.0,1.0,0.01),0.01),"sizing.zero_risk");
   Check(Near(SizingLotsForRisk(-10.0,50.0,1.0,0.01),0.01),"sizing.negative_risk");
   Check(Near(SizingNormalizeVolume(0.237,0.01,0.01,100.0),0.24),"sizing.round_step");
   Check(Near(SizingNormalizeVolume(0.004,0.01,0.01,100.0),0.01),"sizing.clamp_min");
   Check(Near(SizingNormalizeVolume(500.0,0.01,0.01,100.0),100.0),"sizing.clamp_max");
   Check(Near(SizingNormalizeVolume(1.234,1.0,0.01,20.0),1.23),"sizing.min_one_lot");
  }

//--- guard (mirrors tests/bot/test_account_guard.py) -------------------------------
void TestGuard()
  {
   AccountLimits ftmo;
   ftmo.initial_balance=10000.0;
   ftmo.daily_loss_pct=4.0;
   ftmo.max_loss_pct=8.0;
   ftmo.day_reset_rule=TZ_CET_EU_DST;
   ftmo.day_reset_fixed_hours=0;
   GuardVerdict verdict;

   // Python FTMO fixture: initial 10,000, daily 4%, max 8%
   AccountGuardCheck(ftmo,10000.0,0.0,150.0,25.0,verdict);
   Check(verdict.allowed && Near(verdict.worst_day_loss,175.0),"guard.allowed_fresh_day");

   AccountGuardCheck(ftmo,9700.0,-300.0,75.0,50.0,verdict);
   Check(!verdict.allowed && verdict.reason==ALGO_REASON_DAILY
         && Near(verdict.day_start_balance,10000.0),"guard.daily_block");

   // lost 300 yesterday: day_start_balance == balance, worst day loss 125
   AccountGuardCheck(ftmo,9700.0,0.0,75.0,50.0,verdict);
   Check(verdict.allowed,"guard.yesterday_loss_not_today");

   AccountGuardCheck(ftmo,10200.0,200.0,0.0,650.0,verdict);
   Check(!verdict.allowed && verdict.reason==ALGO_REASON_DAILY,"guard.profit_day_still_capped");

   AccountGuardCheck(ftmo,9250.0,0.0,25.0,50.0,verdict);
   Check(!verdict.allowed && verdict.reason==ALGO_REASON_MAX,"guard.max_block");

   AccountLimits off=ftmo;
   off.daily_loss_pct=0.0;
   off.max_loss_pct=0.0;
   AccountGuardCheck(off,1.0,0.0,1e9,1e9,verdict);
   Check(verdict.allowed,"guard.off");
  }

void WriteSummary()
  {
   FolderCreate("AlgoTrading",FILE_COMMON);
   FolderCreate(SELFTEST_RESULT_DIR,FILE_COMMON);
   int handle=FileOpen(SELFTEST_RESULT_DIR+"/S021_selftest.json",
                       FILE_WRITE|FILE_TXT|FILE_ANSI|FILE_COMMON);
   if(handle==INVALID_HANDLE)
      return;
   FileWriteString(handle,StringFormat("{\"passed\":%d,\"failed\":%d,\"params_source\":\"%s\","
                                       "\"first_failures\":[%s]}\n",
                                       g_passed,g_failed,S021_PARAMS_SOURCE,g_failures));
   FileClose(handle);
  }

void OnStart()
  {
   TestClockFixed();
   TestClockFixture();
   TestSizing();
   TestGuard();
   TestLevelsFixture();
   WriteSummary();
   PrintFormat("S021 self-test: %d passed, %d failed -- %s",g_passed,g_failed,
               g_failed==0 ? "OK" : "FAILED");
  }
//+------------------------------------------------------------------+
