"""Generate the MQL5 constant headers from the Python source of truth.

    python -m mt5.tools.gen_params           # (re)write every generated header
    python -m mt5.tools.gen_params --check   # exit 1 if any header is stale

The MQL5 EAs never restate a strategy number by hand: every rule constant
comes from a header produced here from the same dataclass the backtest
engine and the cTrader bot read (code-architecture: single source of truth).
tests/mt5/test_gen_params.py runs the --check logic in CI, so editing a
Python config without regenerating fails the test suite.

Adding a strategy = one more GeneratedHeader in HEADERS (see the S021 entry
for the pattern: an explicit whitelist of the fields the EA implements, and a
guard that every OTHER config field is at its default -- the EA implements
the frozen base only, never a modifier).
"""
from __future__ import annotations

import argparse
import dataclasses
import hashlib
import sys
from dataclasses import dataclass
from datetime import datetime, time
from pathlib import Path
from typing import Callable
from zoneinfo import ZoneInfo

MT5_ROOT = Path(__file__).resolve().parents[1]          # <repo>/mt5
INCLUDE_ROOT = MT5_ROOT / "MQL5" / "Include"
BANNER = "// GENERATED by mt5/tools/gen_params.py -- DO NOT EDIT. Regenerate instead."
MINUTES_PER_HOUR = 60
SECONDS_PER_HOUR = 3600
SOURCE_HASH_CHARS = 12
OFFSET_PROBE_INSTANT = datetime(2020, 1, 1)             # any instant: the zone is fixed-offset

# IANA zone of a strategy's session clock -> the ENUM_TZ_RULE member that
# reproduces it in MQL5 (AlgoCore/Clock.mqh). Keep both sides in step; the
# rules are cross-checked against zoneinfo by tests/mt5/test_clock.py.
SESSION_CLOCK_RULES = {
    "America/New_York": "TZ_EST_US_DST",
}


class _MqlIdentifier(str):
    """Emitted verbatim (an enum member name), never as a quoted string literal."""


@dataclass(frozen=True)
class GeneratedHeader:
    relative_path: str                  # under mt5/MQL5/Include
    render: Callable[[], str]

    @property
    def path(self) -> Path:
        return INCLUDE_ROOT / self.relative_path


# ---------------------------------------------------------------- formatting
def _mql_value(value) -> str:
    if isinstance(value, _MqlIdentifier):
        return str(value)
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        text = str(value)
    elif isinstance(value, float):
        text = repr(value)
        text = text if ("." in text or "e" in text) else text + ".0"
    else:
        text = None
    if text is not None:
        # parenthesise negatives so a macro never pastes into "x - -5" style text
        return f"({text})" if text.startswith("-") else text
    if isinstance(value, str):
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
    raise TypeError(f"no MQL5 literal for {type(value).__name__}: {value!r}")


def _minute_of_day(value: time) -> int:
    return value.hour * MINUTES_PER_HOUR + value.minute


def _define(name: str, value, comment: str) -> str:
    return f"#define {name:<36} {_mql_value(value):<12} // {comment}"


def _guard(relative_path: str) -> str:
    return relative_path.upper().replace("/", "_").replace(".", "_")


def _wrap(relative_path: str, doc: list[str], body: list[str]) -> str:
    guard = _guard(relative_path)
    lines = [BANNER, f"// {relative_path}"] + [f"// {line}" if line else "//" for line in doc]
    lines += [f"#ifndef {guard}", f"#define {guard}", ""] + body + ["", f"#endif // {guard}", ""]
    return "\n".join(lines)


def _source_hash(*objects) -> str:
    digest = hashlib.sha256(repr(objects).encode("utf-8")).hexdigest()
    return digest[:SOURCE_HASH_CHARS]


# ---------------------------------------------------------------- AlgoCore
def render_core() -> str:
    from bot import account_guard, risk

    body = [
        _define("ALGO_MIN_STOP_POINTS", float(risk.MIN_STOP_POINTS),
                "bot/risk.py MIN_STOP_POINTS: below this a stop is 'no real stop'"),
        _define("ALGO_PCT", float(account_guard.PCT), "bot/account_guard.py PCT"),
        _define("ALGO_REASON_DAILY", account_guard.REASON_DAILY,
                "bot/account_guard.py REASON_DAILY (log readers grep for it)"),
        _define("ALGO_REASON_MAX", account_guard.REASON_MAX, "bot/account_guard.py REASON_MAX"),
    ]
    return _wrap("AlgoCore/GeneratedCore.mqh",
                 ["Shared constants from the Python bot base layer (bot/risk.py,",
                  "bot/account_guard.py)."], body)


# ---------------------------------------------------------------- S021
# Fields of OrbConfig the S021 EA implements. Every other field must be at its
# dataclass default in the config being exported (= no modifier enabled).
S021_EA_FIELDS = ("adr_window", "k_range", "stop_adr_mult", "session_open", "session_close",
                  "entry_cutoff", "min_session_bars", "max_gap_days_per_session")
# Backtest-only fields: meaningful to the engine, intentionally absent from the EA
# (live costs are the broker's real spread/commission, not a modelled bps charge).
S021_BACKTEST_ONLY_FIELDS = ("cost_bps_roundtrip",)


def _check_s021_base_only(config) -> None:
    from strategies.orb_intraday.config import OrbConfig

    defaults = OrbConfig()
    enabled = [field.name for field in dataclasses.fields(OrbConfig)
               if field.name not in S021_EA_FIELDS + S021_BACKTEST_ONLY_FIELDS
               and getattr(config, field.name) != getattr(defaults, field.name)]
    if enabled:
        raise ValueError(
            "the S021 EA implements the frozen base only, but the exported config has "
            f"modifier fields away from their defaults: {enabled}. Implement the modifier "
            "in the EA first (and add it to S021_EA_FIELDS), or export ORB_BASE.")


def _fixed_offset_hours(zone_name: str) -> int:
    offset = ZoneInfo(zone_name).utcoffset(OFFSET_PROBE_INSTANT)
    return int(offset.total_seconds() // SECONDS_PER_HOUR)


def render_s021(config=None) -> str:
    from bot import orb_config
    from strategies.orb_intraday import engine
    from strategies.orb_intraday.config import ORB_BASE

    config = ORB_BASE if config is None else config
    _check_s021_base_only(config)
    clock_rule = SESSION_CLOCK_RULES[engine.SESSION_TZ]
    source = (f"strategies/orb_intraday/config.py::ORB_BASE "
              f"sha={_source_hash(config, engine.SESSION_TZ)}")
    body = [
        _define("S021_ADR_WINDOW", config.adr_window, "ORB_BASE.adr_window (sessions)"),
        _define("S021_K_RANGE", config.k_range, "ORB_BASE.k_range: U/L = O +/- k * ADR14"),
        _define("S021_STOP_ADR_MULT", config.stop_adr_mult,
                "ORB_BASE.stop_adr_mult: SL distance = mult * ADR14"),
        _define("S021_SESSION_OPEN_MINUTE", _minute_of_day(config.session_open),
                f"ORB_BASE.session_open {config.session_open:%H:%M} (strategy clock)"),
        _define("S021_SESSION_CLOSE_MINUTE", _minute_of_day(config.session_close),
                f"ORB_BASE.session_close {config.session_close:%H:%M} (strategy clock)"),
        _define("S021_ENTRY_CUTOFF_MINUTE", _minute_of_day(config.entry_cutoff),
                f"ORB_BASE.entry_cutoff {config.entry_cutoff:%H:%M}, last entry minute"),
        _define("S021_MIN_SESSION_BARS", config.min_session_bars,
                "ORB_BASE.min_session_bars (M1 bars in session)"),
        _define("S021_MAX_GAP_DAYS_PER_SESSION", float(config.max_gap_days_per_session),
                "ORB_BASE.max_gap_days_per_session (ADR gap guard)"),
        _define("S021_CLOCK_TZ_RULE", _MqlIdentifier(clock_rule),
                f"engine.SESSION_TZ {engine.SESSION_TZ} (DST-aware exchange local time)"),
        _define("S021_MAGIC_PREFIX", orb_config.MAGIC, "bot/orb_config.py MAGIC (labels)"),
        _define("S021_DEFAULT_RISK_PCT", float(orb_config.RISK_PCT),
                "bot/orb_config.py RISK_PCT (EA input default)"),
        _define("S021_PARAMS_SOURCE", source, "provenance, logged by the EA at init"),
    ]
    return _wrap("Strategies/S021_ORB/Params.mqh",
                 ["S021 (ORB, Nasdaq 100) rule constants. Session minutes are on the",
                  "strategy's America/New_York exchange clock, DST-aware (see",
                  "strategies/orb_intraday/config.py and engine.py's module docstring)."],
                 body)


HEADERS: tuple[GeneratedHeader, ...] = (
    GeneratedHeader("AlgoCore/GeneratedCore.mqh", render_core),
    GeneratedHeader("Strategies/S021_ORB/Params.mqh", render_s021),
)


def stale_headers() -> list[GeneratedHeader]:
    stale = []
    for header in HEADERS:
        current = header.path.read_text(encoding="utf-8") if header.path.exists() else None
        if current != header.render():
            stale.append(header)
    return stale


def write_all() -> list[Path]:
    written = []
    for header in HEADERS:
        content = header.render()
        header.path.parent.mkdir(parents=True, exist_ok=True)
        header.path.write_text(content, encoding="utf-8", newline="\n")
        written.append(header.path)
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if any header is stale")
    args = parser.parse_args(argv)
    if args.check:
        stale = stale_headers()
        for header in stale:
            print(f"STALE: {header.relative_path} -- run python -m mt5.tools.gen_params")
        return 1 if stale else 0
    for path in write_all():
        print(f"wrote {path.relative_to(MT5_ROOT.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
