// GENERATED by mt5/tools/gen_params.py -- DO NOT EDIT. Regenerate instead.
// Strategies/S021_ORB/Params.mqh
// S021 (ORB, Nasdaq 100) rule constants. Session minutes are on the
// strategy's America/New_York exchange clock, DST-aware (see
// strategies/orb_intraday/config.py and engine.py's module docstring).
#ifndef STRATEGIES_S021_ORB_PARAMS_MQH
#define STRATEGIES_S021_ORB_PARAMS_MQH

#define S021_ADR_WINDOW                      14           // ORB_BASE.adr_window (sessions)
#define S021_K_RANGE                         0.2          // ORB_BASE.k_range: U/L = O +/- k * ADR14
#define S021_STOP_ADR_MULT                   0.75         // ORB_BASE.stop_adr_mult: SL distance = mult * ADR14
#define S021_SESSION_OPEN_MINUTE             570          // ORB_BASE.session_open 09:30 (strategy clock)
#define S021_SESSION_CLOSE_MINUTE            959          // ORB_BASE.session_close 15:59 (strategy clock)
#define S021_ENTRY_CUTOFF_MINUTE             869          // ORB_BASE.entry_cutoff 14:29, last entry minute
#define S021_MIN_SESSION_BARS                350          // ORB_BASE.min_session_bars (M1 bars in session)
#define S021_MAX_GAP_DAYS_PER_SESSION        2.5          // ORB_BASE.max_gap_days_per_session (ADR gap guard)
#define S021_CLOCK_TZ_RULE                   TZ_EST_US_DST // engine.SESSION_TZ America/New_York (DST-aware exchange local time)
#define S021_MAGIC_PREFIX                    "S021"       // bot/orb_config.py MAGIC (labels)
#define S021_DEFAULT_RISK_PCT                0.5          // bot/orb_config.py RISK_PCT (EA input default)
#define S021_PARAMS_SOURCE                   "strategies/orb_intraday/config.py::ORB_BASE sha=3d6089ccc700" // provenance, logged by the EA at init

#endif // STRATEGIES_S021_ORB_PARAMS_MQH
